name: login_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  flutter_redux: ^0.10.0
  redux_persist: ^0.9.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  redux: ^5.0.0
  flutter_secure_storage: ^9.2.4
  redux_persist_flutter: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.11.0
  test: ^1.25.15

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
